# Generated by Django 2.1 on 2019-09-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_buttonconfig', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=200)),
                ('link_href', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
