# Generated by Django 2.1 on 2019-10-01 09:39

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0007_navmenuconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavSimpleItemConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_navsimpleitemconfig', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('link_page', cms.models.fields.PageField(on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
