# Generated by Django 2.1 on 2019-10-01 13:09

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0008_navsimpleitemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavDeeplinkItemConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_navdeeplinkitemconfig', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('link_format', models.CharField(choices=[('short', 'Short (columns)'), ('long', 'Long (full-width)')], max_length=8)),
                ('summary_link_label', models.CharField(blank=True, max_length=100)),
                ('summary_link_target', cms.models.fields.PageField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
