# Generated by Django 2.1 on 2019-10-01 13:49

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0009_navdeeplinkitemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavImageItemConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_navimageitemconfig', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('link_page', cms.models.fields.PageField(on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
