# Generated by Django 2.1 on 2019-10-02 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('zf_plugins', '0010_navimageitemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_featureconfig', serialize=False, to='cms.CMSPlugin')),
                ('header', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, choices=[(None, '-'), ('book', 'Book'), ('calendar', 'Calendar'), ('chat', 'Chat'), ('feed', 'Feed'), ('info', 'Info'), ('money', 'Money'), ('person', 'Person'), ('pin', 'Pin'), ('point', 'Point'), ('question', 'Question'), ('share', 'Share'), ('sound', 'Sound'), ('time', 'Time')], max_length=20, null=True)),
                ('text', models.TextField()),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
