# Generated by Django 2.1 on 2019-10-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0011_featureconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeadConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='zf_plugins_sectionheadconfig', serialize=False, to='cms.CMSPlugin')),
                ('header', models.CharField(max_length=100)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
