# Generated by Django 2.1 on 2019-10-03 09:00

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('zf_plugins', '0014_simpleheroconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenuconfig',
            name='section_page',
            field=cms.models.fields.PageField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
            preserve_default=False,
        ),
    ]
