# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 15:00
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_plugins_blurb', serialize=False, to='cms.CMSPlugin')),
                ('headline', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('link', cms.models.fields.PageField(on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
