# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_plugins', '0002_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_plugins.Icon'),
            preserve_default=False,
        ),
    ]
