# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_plugins', '0003_blurb_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='link_text',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
