# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_plugins', '0004_blurb_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('button', 'Button')], default='link', max_length=8),
        ),
    ]
